### ISSUE TITLE
run_cistarget: "unable to load annotation" with mm10 aertslab ctx_db/annotations

### ISSUE THREAD

**Issue by chooliu** [aertslab/pycistarget#10]
**Describe the bug**

I was running a small input .bedfile test set largely following the pycistarget mouse liver [ChIP-seq tutorial](https://pycistarget.readthedocs.io/en/latest/pycistarget_chip-RTD.html), including the pre-made aertslab mm10 ctx_db and annotation files from the tutorial. I came across what appears to be a warning using `run_cistarget()`: "Unable to load annotation for mus_musculus." 

Nothing in the output is obviously wrong, so just wanted to just check if that database format is working as intended and if this indeed is just a warning (versus error). 

Thanks & excited to keep trying out SCENIC/cistarget!

**To Reproduce**

downloaded:
* https://resources.aertslab.org/cistarget/databases/mus_musculus/mm10/screen/mc_v10_clust/region_based/mm10_screen_v10_clust.regions_vs_motifs.rankings.feather
* https://resources.aertslab.org/cistarget/motif2tf/motifs-v10nr_clust-nr.mgi-m0.001-o0.0.tbl

script:
```
import pyranges as pr
import pandas as pd
from pycistarget.motif_enrichment_cistarget import *

DMRs = pd.read_csv("testcase.bed", usecols = range(0, 3))
DMRs.set_axis(["Chromosome", "Start", "End"], axis = 1, inplace = True)
region_sets = {"AllDMRs": pr.PyRanges(DMRs)}

cistarget_dict = run_cistarget(ctx_db = 'mm10_screen_v10_clust.regions_vs_motifs.rankings.feather',
                                    region_sets = region_sets,
                                    specie = 'mus_musculus',
                                    auc_threshold = 0.005,
                                    nes_threshold = 3.0,
                                    rank_threshold = 0.05,
                                    annotation = ['Direct_annot', 'Orthology_annot'],
                                    annotation_version = 'v10nr_clust',
                                    path_to_motif_annotations = 'motifs-v10-nr.mgi-m0.00001-o0.0.tbl',
                                    n_cpu = 4,
                                    _temp_dir = '/u/home/scratch/')
```

**Error output**
Paste the entire output of the command, including log information prior to the error.
```
2022-10-06 13:40:25,699 cisTarget    INFO     Reading cisTarget database
2022-10-06 13:41:02,864 INFO worker.py:1509 -- Started a local Ray instance. View the dashboard at ESC[1mESC[32mhttp://127.0.0.1:8265 ESC[39mESC[22m
ESC[2mESC[36m(ctx_internal_ray pid=156036)ESC[0m 2022-10-06 13:41:05,834 cisTarget    INFO     Running cisTarget for AllDMRs which has 114 regions
ESC[2mESC[36m(ctx_internal_ray pid=156036)ESC[0m 2022-10-06 13:41:22,408 cisTarget    INFO     Annotating motifs for AllDMRs
ESC[2mESC[36m(ctx_internal_ray pid=156036)ESC[0m 2022-10-06 13:41:22,412 cisTarget    INFO     Unable to load annotation for mus_musculus
2022-10-06 13:41:25,099 cisTarget    INFO     Done!

```

**Screenshots**
Example output:
```
cistarget_results(cistarget_dict)
```
<img width="842" alt="screenshot of cistarget_results" src="https://user-images.githubusercontent.com/9291548/194440808-735f77c1-03b2-4139-8ad9-ca645bb70e2f.png">

**Version (please complete the following information):**
 - Python 3.8.13
 - Pycistarget: 1.0.2.dev9+g0ed8289

**Comment by SeppeDeWinter** [comment]
Hi @chooliu 

Did you download the following file `motifs-v10-nr.mgi-m0.00001-o0.0.tbl`. The function is trying to load this, but if you did not download it (and put it in your working directory) it won't be able to.

If you did not download that file, you can also set `path_to_motif_annotations` to `None` and the function will fetch the annotations automatically from the web.

Hope this helps!

Best,

Seppe

**Comment by chooliu** [comment]
Oops--this is an embarrassing one, but the error was simply that the current motifs file on the aertslab is ".mgi-m0.001-o0.0.tbl" versus the tutorial's  ".mgi-m0.00001", and I didn't catch the naming difference (could potentially consider updating tutorial to match new naming conventions?).

Correcting the motif filepath argument in, I no longer get the INFO line and get the "Direct_annot" and "Orthology_annot" columns on my cistarget_results() output.

Thanks you for the support and fast response Seppe!!
