### ISSUE TITLE
ValueError: Length mismatch: Expected axis has 0 elements, new values have 3 elements

### ISSUE THREAD

**Issue by Citugulia40** [aertslab/pycistarget#22]
Hi, 

I am getting an errors running Scenic+ pipeline on pbmc multiome data which I have also asked on Scenic+ issues

https://github.com/aertslab/scenicplus/issues/183
https://github.com/aertslab/scenicplus/issues/182

Can you please help me with these?

Thanks

**Comment by SeppeDeWinter** [comment]
Hi @Citugulia40 

Please don't duplicate issues. 
I've responded to your questions on the SCENIC+ repo.

I'm closing this issue.

Best,

Seppe
