### ISSUE TITLE
Normalized Enrichment Scores (NES)

### ISSUE THREAD

**Issue by Leticia314** [aertslab/pycistarget#39]
Hi! Thank you for developing such a great tool! 
I was wondering, is there any easy way to extract the Normalized Enrichment Scores (NES) for the different motifs so that they can be explored with other tools, like R?
Thank you!

**Comment by SeppeDeWinter** [comment]
Hi @Leticia314 

Yes, that's possible.

use `--output_mode tsv` to write a tab-seperated file containing NES values.

All the best,

Seppe

**Comment by Leticia314** [comment]
Thank you very much!
